import type { Metadata } from "next";
import { ReactNode } from 'react';
import Link from 'next/link';
import './globals.css';
import { Inter } from "next/font/google";
import "./globals.css";
import "./fonts.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <div className="main-header container">
            <div>
              <Link href="/">Home</Link>
            </div>
            <div>
              <Link href="/Cryptolytics">Cryptolytics</Link>
            </div>
            <div>
              <Link href="/About">About</Link>
            </div>
          </div>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
